name: Build extension
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Stage Chrome manifest
        run: cp src/manifest.chrome.json src/manifest.json

      - uses: actions/upload-artifact@v4
        with:
          name: crumble-chrome
          path: ./src/*

      - name: Stage Firefox manifest
        run: cp src/manifest.firefox.json src/manifest.json

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: src
          filename: "crumble.xpi"

      - uses: actions/upload-artifact@v4
        with:
          name: crumble-firefox-source
          path: ./src/*

      - uses: actions/upload-artifact@v4
        with:
          name: crumble-firefox-unsigned
          path: ${{ steps.web-ext-build.outputs.target }}
